services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    tty: true
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "7860:7860"
    entrypoint: python /app/gui_app.py
    